[[profile]]
name = "office-desk"
exec = ["notify-send \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = true
search = ["m=0xE48D", "s=", "v=AU Optronics"]
mode = "1920x1080@60.052Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = ["swayws range --numeric 1 2 $SHIKANE_OUTPUT_NAME", "swayws move --numeric 9 $SHIKANE_OUTPUT_NAME"]

[[profile.output]]
enable = true
search = ["m=DELL P2720DC", "s=2P7TL93", "v=Dell Inc."]
mode = "2560x1440@59.951Hz"
position = "1920,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
exec = ["swayws range --numeric 3 8 $SHIKANE_OUTPUT_NAME", "swayws move --numeric 10 $SHIKANE_OUTPUT_NAME"]
