[colors.bright]
black = "0x2f4f4f"
blue = "0x0000bf"
cyan = "0x00e6e6"
green = "0x009600"
magenta = "0xbf00bf"
red = "0xbf0000"
white = "0xe6e6e6"
yellow = "0xffa600"

[colors.normal]
black = "0x111a1a"
blue = "0x00008b"
cyan = "0x00ced1"
green = "0x006400"
magenta = "0x8b008b"
red = "0x8b0000"
white = "0xb3b3b3"
yellow = "0xe4a010"

[colors.primary]
background = "0xfcfcfc"
foreground = "0x050505"

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5
