-- Heavily inspired by https://github.com/MarioCarrion/videos/tree/main/2023/01/nvim
require("core")
require("plugins.barbar")
require("plugins.lualine")
require("plugins.github-theme")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.nvim-treesitter")
require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.go")
require("plugins.comment")
require("plugins.null-ls")
require("plugins.markdown")
require("plugins.autopairs")
